name: dbt_ecommerce_dw
version: '1.0'
profile: ecommerce_dw

model-paths: ["dbt_ecommerce_dw/models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data/raw"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]